### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by akashkj** [elvistony/jio-pyserver#7]
Hey I tried to run this in local setup but stream doesn't load. Is it still working?

**Comment by elvistony** [comment]
Hey @akashkj ,
It appears to be the login issue, apparently Jio has removed the password login mode from the app. 
I'm not sure if I can include OTP Authentication to this project either.

**Comment by mayankwadhwani** [comment]
Hi @elvistony , I'd like to pick up the issue on OTP based authentication. Need some help though. Can we connect sometime ?

**Comment by elvistony** [comment]
Hey @mayankwadhwani, I'm a bit caught up some other work at the moment, feel free to raise a pull request.

**Comment by elvistony** [comment]
The Script seems to be working now, I'm closing this issue for now, reopen this issue if it still persists.
